---
- name: Spin up a new server on EC2
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: Launch instance
      local_action:
        module: ec2
        instance_type: m3.medium
        key_name: ansible_gatewayd
        image: ami-29ebb519
        region: us-west-2
        wait: yes
        group_id: sg-2d633848
        count: 1
        assign_public_ip: yes
        vpc_subnet_id: subnet-93594ae7
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: Add tag to instances
      local_action: ec2_tag resource={{ item.id }} region=us-west-2 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: gwd

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure new gatewayd
  hosts: launched
  user: ubuntu
  sudo: True
  gather_facts: True
  roles:
    - common
    - node-js
    - postgres
    - nginx
    - gatewayd