---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a set of instances
      ec2:
         #ssh key to use on the new machine
         key_name: nathan_reese_gatewayzen
         instance_type: t1.micro
         image: ami-37501207
         wait: true
         region: us-west-2
         group: sg-7f4a041a
         vpc_subnet_id: subnet-301fc147
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2
