---
- name: Deploy new gatewayd instance -- install gatewayd, install global dependencies and configure application
  hosts: webservers
  remote_user: ubuntu
  sudo: yes
  roles:
    - node-js
    - postgres
    - nginx
    - gatewayd