---
- name: ensure apt cache is up to date
  action: apt update_cache=yes

- name: Base OS packages
  apt: name={{ item }} state=present
  with_items:
   - git
   - python-software-properties
   - python
   - g++
   - make